on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish-release:
    runs-on: codeberg-tiny
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install all dependencies
        run: pnpm install

      - name: Build project
        run: |
          pnpm run build
          pnpm run pack

      - name: Release
        uses: actions/forgejo-release@v2
        with:
          release-dir: ./.release/
          direction: upload
          tag: ${{ github.ref_name }}
          token: ${{ secrets.FORGEJO_TOKEN }}
